### PR TITLE
Stop pinning urllib3 (only done for testing dep)

### PR DESCRIPTION
**Pull request by DavidCain**
This fixes a problem where one cannot install `bioutils` into an
environment where `urllib3` version 2 is being used. In other words,
merely installing `bioutils` forces you to use `urllib3` version 1.

There's a positive side effect too where installing `bioutils` no longer
pulls in an unneeded dependency.

Why are we pinning an unused dependency?
========================================
Previously, `vcrpy` (a test dependency) would not support urllib3
version 2. Tests would fail to run because of an attempted import of
`urllib3.connectionpool.VerifiedHTTPSConnection` (not present in v2):
https://github.com/biocommons/bioutils/issues/46#issuecomment-1535482771

To resolve the error, `urllib3` was pinned to version `1.26.*`:
https://github.com/biocommons/bioutils/pull/49

This definitely worked, but `urllib3` is *not* directly used by the
package, only indirectly used during testing.

Why pin a transitive test-only dependency?
==========================================
Unfortunately, the way that `urllib3` was pinned doesn't just affect CI
for this repository, but affects *any* environment in which `bioutils`
is installed. Specifically, `urllib3` will *always* be installed as a
dependency (or possibly downgraded from v2) when you `pip install bioutils`!

There are ways we could have pinned `urllib3` only in CI without
affecting package dependencies, but that's not important anymore.

Is the original problem solved?
===============================
Yes! `vcrpy` version 4.3.1 (released in May of 2023) started supporting
`urllib3` version 2!

> Support urllib3 v1 and v2. NOTE: there is an issue running urllib3 v2
> on Python older than 3.10, so this is currently blocked in the
> requirements. Hopefully we can resolve this situation in the future.
> Thanks to shifqu, hartwork, jairhenrique, pquentin, and vEpiphyte for
> your work on this.

https://vcrpy.readthedocs.io/en/latest/changelog.html

### CODE REVIEW

**Review by andreasprlic — DISMISSED** [review]
Looks like this change is breaking the unit tests

**Comment by DavidCain** [comment]
Thanks for the review and for triggering CI, @andreasprlic - I can take a look at the failing unit tests and try to sort it out soon.

**Comment by jsstevenson** [comment]
fwiw, behavior looks correct to me when I test manually -- I wonder if the cassettes need to be regenerated?

**Review by korikuzma — DISMISSED** [review]

**Comment by DavidCain** [comment]
Thank you! @andreasprlic - tests do seem to be passing now.

**Comment by andreasprlic** [comment]
Somehow I am jinxing this. The tests fail in the CI. Should we try regenerating the cassettes, as @jsstevenson suggested?

**Comment by ahwagner** [comment]
Removing `stale` this time; @DavidCain please try regenerating the cassettes for this PR or requesting help to do so if needed.

**Comment by DavidCain** [comment]
> Removing `stale` this time; @DavidCain please try regenerating the cassettes for this PR or requesting help to do so if needed.

Thank you, @ahwagner -- I'll confess that I have no idea what "cassettes" even mean in this context so I will gladly take assistance!

**Comment by ahwagner** [comment]
This should be good to go now, and is ready for re-review. I also added in a fix to the makefile to build virtual env properly.

**Review by andreasprlic — APPROVED** [review]
LGTM

**Comment by DavidCain** [comment]
Thank you all so much! Any idea when we might be able to get a new release of `bioutils` so that `urllib3` version 2 can be used?

**Comment by andreasprlic** [comment]
doing a release should be easy (just placing a git tag). Let me try that.

**Pull request merged**
