### PR TITLE
Rewrite trim_left and trim_right for linear performance.

### PR DESCRIPTION
**Pull request by theferrit32**
This improves the performance of `trim_left` and `trim_right` to eliminate array copies/modifications except for the last one in the return value.

It also adds handling of the case when an empty collection of alleles are passed, by returning `(0, [])`

### CODE REVIEW

**Review by larrybabb — APPROVED** [review]
awesome job. let's get this merged asap.

**Comment by larrybabb** [comment]
@andreasprlic and/or @ahwagner can either of you review and merge this change from Kyle? It is a major improvement to the left/right trimming performance.

**Comment by reece** [comment]
I'll look later this morning.

**Review by reece — APPROVED** [review]
Looks great to me, @theferrit32 . Thanks!

**Pull request merged**
