### PR TITLE
passable docstrings

### PR DESCRIPTION
**Pull request by trentwatt**

### CODE REVIEW

**Comment by reece** [comment]
@trentwatt: These changes look *great*! Thank you.

travis has started failing. I haven't perused all of the failures, but they're likely simple. Would you like to try to fix?

Please push any changes you make onto the same branch. This PR will be automatically updated and we can preserve the this discussion.

Again, thanks!

**Comment by trentwatt** [comment]
Ok, sure. I'll see what I can do.

**Comment by reece** [comment]
@trentwatt: So sorry for the long delay! I'll reply by email too in a moment.

I suspect that the underlying sequence has changed. This is extremely rare, but can happen when not using versioned sequence accessions (the version is what's after the period).

Please drop the ENST test. Presuming that succeeds, I'll merge and then add a new test with a versioned accession.

Thanks!

**Comment by trentwatt** [comment]
Ok, all good!

**Comment by reece** [comment]
Awesome. I greatly appreciate your effort and perseverance! Thank you!

**Pull request merged**
