### PR TITLE
adding vertebrate mitochondrial translate table

### PR DESCRIPTION
**Pull request by veenarajaraman**
- Added the vertebrate mitochondrial translation table plus tests

### CODE REVIEW

**Review by andreasprlic — DISMISSED** [review]
Thanks, LGTM!

**Review by andreasprlic — DISMISSED** [review]
I merged in #57 to make sure the CI passes again.

**Comment by andreasprlic** [comment]
I can approve, but don't have permissions to merge this PR.

**Review by reece — APPROVED** [review]
lgtm

**Pull request merged**
